### ISSUE TITLE
Gulp task finishes after the gulp task finishes

### ISSUE THREAD

**Issue by bitplanets** [vgamula/gulp-cucumber#11]
[14:29:52] Using gulpfile \gulpfile.js
    [14:29:52] Starting 'unit-test'...
    [14:29:52] Finished 'unit-test' after 22 ms

    Feature: a
       ....

I think the gulp task should end after the cucumber tests.

**Comment by vgamula** [comment]
Hi! v 0.0.7 fixes this problem

**Comment by Aomitayo** [comment]
Hi! I think this problem is back with 0.0.10
