### ISSUE TITLE
Piping results to file

### ISSUE THREAD

**Issue by jimCresswell** [vgamula/gulp-cucumber#17]
Hello,

Do you have any suggestions for piping the results to file?

**Comment by vgamula** [comment]
Hello,

You can try something like this:
```js
var spawn = require('child_process').spawn;
var fs = require('fs');

gulp.task('cucumber-to-file', function(cb) {
    var baseEncoding = 'utf8';
    var fileStream = fs.createWriteStream('cucumber-result.txt', {
        encoding: baseEncoding
    });
    var chunks = [];
    var stream = spawn('gulp', ['cucumber']);
    
    stream.stdout.setEncoding(baseEncoding);
    stream.stderr.setEncoding(baseEncoding);
    
    stream.stderr.pipe(fileStream);
    stream.stdout.pipe(fileStream);

    stream.on('close', function(e) {
        fileStream.end();
        cb(e);
    });
});
```

where `gulp cucumber` is the next task:
```js
gulp.task('cucumber', function() {
    return gulp.src('features/*').pipe(cucumber({
        'steps': 'features/step_definitions/*_steps.js',
        'support': 'features/support/*.js',
        'format': 'summary',
        'tags': ['@gulpcucumber', '~@wip']
    }));
});
```

**Comment by vgamula** [comment]
`gulp-cucumber` uses `Cucumber.Cli` inside, it writes all results to `process.stdout` and `process.stderr`, so we can't set a hook on stream's `data` event and catch data by the chunks. The only way to do it - create child process and read its `stdout`, `stderr` as I shown in comment above.

**Comment by jimCresswell** [comment]
Thanks very much, I appreciate it! I was thinking of spawning a process but
doing it through Gulp again is neat. Hopefully once Cucumber supports
arbitrary plugins a stream based reporter could be passed in.

Thanks again!
