### ISSUE TITLE
Can you merge in https://github.com/vgamula/gulp-cucumber/pull/29

### ISSUE THREAD

**Issue by tamsayers** [vgamula/gulp-cucumber#31]
Cucumber build not exiting with 1 on failure.  The pull request https://github.com/vgamula/gulp-cucumber/pull/29 fixes this.  Can it be merged in please.

**Comment by vgamula** [comment]
Yeah, just merged, sorry for beeing so late and thanks for reminding me.
Published version 0.0.18

**Comment by tamsayers** [comment]
Thanks for your quick response
